In [1]:
import yaml
def load_yaml(path):
    with open(path, mode='r') as file:
        return yaml.load(file, Loader=yaml.FullLoader)
    
config = load_yaml('extra/config.yaml')

In [2]:
%run features.ipynb
%run processing.ipynb
%run dataSplitScale.ipynb

In [3]:
config

{'data': 'extra/EURUSD2m.csv',
 'processing': {'resample': True,
  'time': 'D',
  'aggregate': {'Open': 'first',
   'High': 'max',
   'Low': 'min',
   'Close': 'last',
   'Volume': 'sum'},
  'label': {'from': 'Close', 'shift': 1}},
 'features': {'category': 'all',
  'window': {'windowtype': 'default',
   'timeframe': 14,
   'windowframes': {'stock': 14,
    'stocd': 3,
    'stocsd': 3,
    'momentum': 10,
    'roc': 14,
    'lwr': 14,
    'disp1': 5,
    'disp2': 10,
    'cci': 14,
    'rsi': 14,
    'ma': 5,
    'bias': 6,
    'psy': 12,
    'asy5': 5,
    'asy4': 4,
    'asy3': 3,
    'asy2': 2,
    'asy1': 1}}},
 'splitting': {'train_split': 0.8, 'validation_folds': 5},
 'regression_ensemble': {'models': [{'linreg': None},
   {'lstm': {'morph': {'window': 4, 'batch': 30},
     'layers': [{'lstm': {'units': 120}},
      {'dropout': {'rate': 0.15}},
      {'dense': {'units': 50, 'activation': 'relu'}},
      {'dense': {'units': 1}}],
     'epochs': 15,
     'loss': 'mean_squared_error',
     'optimizer': 'rmsprop'}},
   {'tcn': {'morph': {'window': 4, 'batch': 30},
     'layers': [{'tcn': {'nb_filters': 64,
        'nb_stacks': 1,
        'dilations': [1, 2, 4, 8, 16, 32],
        'padding': 'causal',
        'use_skip_connections': False,
        'dropout_rate': 0.1,
        'return_sequences': False}},
      {'dropout': {'rate': 0.05}},
      {'dense': {'units': 50, 'activation': 'relu'}},
      {'dense': {'units': 1}}],
     'epochs': 15,
     'loss': 'mean_squared_error',
     'optimizer': 'adam'}}]},
 'classification_ensemble': {'decision': {'upper': 0.75, 'lower': 0.25},
  'models': [{'randforest': {'grid_search': {'n_estimators': [10,
       50,
       100,
       300],
      'max_features': ['log2', 'sqrt'],
      'max_depth': [10, 100, 'None'],
      'min_samples_split': [3, 10],
      'min_samples_leaf': [2, 4],
      'bootstrap': [True, False],
      'class_weight': ['balanced']}}},
   {'logreg': {'static': {'random_state': 0, 'class_weight': 'balanced'}}},
   {'svc': {'static': {'decision_function_shape': 'ovo'},
     'grid_search': {'kernel': ['linear', 'rbf'], 'C': [1, 150]}}}]}}

In [4]:
df = create_dataframe(config)

In [5]:
df.head(5)

                   Open     High      Low    Close        Volume    label
Date_Timestamp
2010-01-01      1.43327  1.43356  1.43207  1.43335  39761.000053  1.43141
2010-01-03      1.43024  1.43359  1.42951  1.43141   3001.600003  1.44244
2010-01-04      1.43143  1.44556  1.42559  1.44244  80019.400094  1.43634
2010-01-05      1.44238  1.44834  1.43445  1.43634  79887.100067  1.44005
2010-01-06      1.43638  1.44342  1.42807  1.44005  80971.800085  1.43155

In [6]:
df.isnull().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
label     0
dtype: int64

In [7]:
rd = add(df, config['features'])

In [8]:
rd.head(5)

,open,high,low,close,volume,label,stock,stocd,stocsd,momentum,...,rsi,obv,ma,bias6,psy12,asy5,asy4,asy3,asy2,asy1
Date_Timestamp,,,,,,,,,,,,,,,,,,,,,
2010-01-21,1.41115,1.41422,1.40247,1.40979,78980.100041,1.41361,13.189189,9.578919,19.849579,-0.02655,...,29.873956,-159980.600046,1.425180,-0.012336,41.7,-0.403064,-0.471831,-0.715772,-0.637503,-0.099256
2010-01-22,1.40977,1.41805,1.40837,1.41361,76660.300037,1.41517,20.072072,13.339429,14.445538,-0.02644,...,33.983332,-83320.300009,1.420572,-0.006774,41.7,-0.323346,-0.469180,-0.334804,0.085670,0.270596
2010-01-24,1.41557,1.41705,1.41396,1.41517,3128.600004,1.41458,22.882883,18.714715,13.877688,-0.01638,...,35.641946,-80191.700005,1.415528,-0.003171,33.3,-0.353285,-0.223529,0.093878,0.190445,0.110295
2010-01-25,1.41498,1.41939,1.41248,1.41458,79577.200048,1.40808,21.819820,21.591592,17.881912,-0.02625,...,35.280916,-159768.900053,1.412868,-0.000558,33.3,-0.187163,0.059984,0.113064,0.034298,-0.041700
2010-01-26,1.41454,1.41780,1.40397,1.40808,79232.600053,1.40280,10.108108,18.270270,19.525526,-0.03823,...,31.495786,-239001.500106,1.412246,-0.002826,25.0,-0.044125,-0.030342,-0.130655,-0.251130,-0.460559